doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '18'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        enable_native_lazy_objects: true
        enable_lazy_ghost_objects: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        controller_resolver:
            auto_mapping: false
        mappings:
            User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Feature/User/Entity'
                prefix: 'App\Feature\User\Entity'
                alias: User
            Organization:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Feature/Organization/Entity'
                prefix: 'App\Feature\Organization\Entity'
                alias: Organization
            Room:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Feature/Room/Entity'
                prefix: 'App\Feature\Room\Entity'
                alias: Room
            Booking:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Feature/Booking/Entity'
                prefix: 'App\Feature\Booking\Entity'
                alias: Booking
            Issue:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Feature/Issue/Entity'
                prefix: 'App\Feature\Issue\Entity'
                alias: Issue

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
