services:
  roomctrl-php:
    container_name: roomctrl-php
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - roomctrl-uploads:/var/www/html/public/uploads/rooms
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_DEBUG: ${APP_DEBUG:-1}
    depends_on:
      - roomctrl-postgres
      - roomctrl-mailhog
    networks:
      - roomctrl-network

  roomctrl-nginx:
    container_name: roomctrl-nginx
    restart: unless-stopped
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - roomctrl-php
    networks:
      - roomctrl-network

  roomctrl-postgres:
    container_name: roomctrl-postgres
    restart: unless-stopped
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-roomctrl_dev}
      POSTGRES_USER: ${POSTGRES_USER:-roomctrl}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-roomctrl123}
    ports:
      - "5432:5432"
    volumes:
      - roomctrl-postgres-data:/var/lib/postgresql/data
    networks:
      - roomctrl-network

  roomctrl-mailhog:
    container_name: roomctrl-mailhog
    restart: unless-stopped
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - roomctrl-network

networks:
  roomctrl-network:
    driver: bridge

volumes:
  roomctrl-postgres-data:
    driver: local
  roomctrl-uploads:
    driver: local
